'use strict';
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, '__esModule', {value: true});
exports.IFoundationTreasuryNode__factory = void 0;
const ethers_1 = require('ethers');
const _abi = [
  {
    inputs: [],
    name: 'getFoundationTreasury',
    outputs: [
      {
        internalType: 'address payable',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
class IFoundationTreasuryNode__factory {
  static createInterface() {
    return new ethers_1.utils.Interface(_abi);
  }
  static connect(address, signerOrProvider) {
    return new ethers_1.Contract(address, _abi, signerOrProvider);
  }
}
exports.IFoundationTreasuryNode__factory = IFoundationTreasuryNode__factory;
IFoundationTreasuryNode__factory.abi = _abi;
//# sourceMappingURL=IFoundationTreasuryNode__factory.js.map
