"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IncomingTransferSupportV1__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_erc20TransferHelper",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [],
        name: "erc20TransferHelper",
        outputs: [
            {
                internalType: "contract ERC20TransferHelper",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
const _bytecode = "0x60a060405234801561001057600080fd5b5060405161013a38038061013a83398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b60805160b261008860003960006031015260b26000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638f9d325114602d575b600080fd5b60537f000000000000000000000000000000000000000000000000000000000000000081565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f3fea2646970667358221220bec6b4e398e175953849e488631c4848d7652a74bc37a7ddaa2e007fba5b343a64736f6c634300080a0033";
const isSuperArgs = (xs) => xs.length > 1;
class IncomingTransferSupportV1__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(_erc20TransferHelper, overrides) {
        return super.deploy(_erc20TransferHelper, overrides || {});
    }
    getDeployTransaction(_erc20TransferHelper, overrides) {
        return super.getDeployTransaction(_erc20TransferHelper, overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IncomingTransferSupportV1__factory = IncomingTransferSupportV1__factory;
IncomingTransferSupportV1__factory.bytecode = _bytecode;
IncomingTransferSupportV1__factory.abi = _abi;
//# sourceMappingURL=IncomingTransferSupportV1__factory.js.map