"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IRaribleV2__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "id",
                type: "uint256",
            },
        ],
        name: "getRaribleV2Royalties",
        outputs: [
            {
                components: [
                    {
                        internalType: "address payable",
                        name: "account",
                        type: "address",
                    },
                    {
                        internalType: "uint96",
                        name: "value",
                        type: "uint96",
                    },
                ],
                internalType: "struct IRaribleV2.Part[]",
                name: "",
                type: "tuple[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IRaribleV2__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IRaribleV2__factory = IRaribleV2__factory;
IRaribleV2__factory.abi = _abi;
//# sourceMappingURL=IRaribleV2__factory.js.map