"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SuperRareContracts__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "SUPERRARE_REGISTRY",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "SUPERRARE_V1",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "SUPERRARE_V2",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
const _bytecode = "0x60f9610039600b82828239805160001a60731461002c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c806389f796ba14604c578063d236782314608f578063f19312ff1460a9575b600080fd5b606673b932a70a57673d89f4acffbe830e8ed7f75fb9e081565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b60667317b0c8564e53f22364a6c8de6f7ca5ce9bea4e5d81565b60667341a322b28d0ff354040e2cbc676f0320d8c8850d8156fea26469706673582212202fb7f8e0e906999a05c23bfa4f3961c01b38fa4a551ed0b13d90d49d19f1ef8764736f6c634300080a0033";
const isSuperArgs = (xs) => xs.length > 1;
class SuperRareContracts__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.SuperRareContracts__factory = SuperRareContracts__factory;
SuperRareContracts__factory.bytecode = _bytecode;
SuperRareContracts__factory.abi = _abi;
//# sourceMappingURL=SuperRareContracts__factory.js.map