"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UniversalExchangeEventV1__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "userA",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "userB",
                type: "address",
            },
            {
                components: [
                    {
                        internalType: "address",
                        name: "tokenContract",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "tokenId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256",
                    },
                ],
                indexed: false,
                internalType: "struct UniversalExchangeEventV1.ExchangeDetails",
                name: "a",
                type: "tuple",
            },
            {
                components: [
                    {
                        internalType: "address",
                        name: "tokenContract",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "tokenId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256",
                    },
                ],
                indexed: false,
                internalType: "struct UniversalExchangeEventV1.ExchangeDetails",
                name: "b",
                type: "tuple",
            },
        ],
        name: "ExchangeExecuted",
        type: "event",
    },
];
const _bytecode = "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212209f35c440adf39942d157f8412748d99e114dda73d80b5dfb526091163762e64064736f6c634300080a0033";
const isSuperArgs = (xs) => xs.length > 1;
class UniversalExchangeEventV1__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.UniversalExchangeEventV1__factory = UniversalExchangeEventV1__factory;
UniversalExchangeEventV1__factory.bytecode = _bytecode;
UniversalExchangeEventV1__factory.abi = _abi;
//# sourceMappingURL=UniversalExchangeEventV1__factory.js.map