/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema defined version 20220222 of the Catalog Metadata Schema
 */
export interface Mnft20220222 {
  /**
   * The version of the schema
   */
  version: "mnft-20220222";
  /**
   * The title of the track
   */
  title: string;
  /**
   * The artist of the track
   */
  artist?: string;
  /**
   * The description of the track
   */
  description?: string;
  /**
   * The duration of the track in seconds
   */
  duration: number;
  /**
   * The mime type of the content file
   */
  mimeType: string;
  /**
   * The track number of the track
   */
  trackNumber?: number;
  /**
   * The project that the track belongs to
   */
  project?: {
    /**
     * The title of the project
     */
    title: string;
    /**
     * The artwork of the project
     */
    artwork?: {
      /**
       * The uri of the artwork (ipfs://<CID>)
       */
      uri?: string;
      /**
       * The mime type of the artwork
       */
      mimeType: string;
      /**
       * The NFT of the artwork (caip19)
       */
      nft?: string;
      [k: string]: unknown;
    };
    /**
     * The description of the project
     */
    description?: string;
    /**
     * The type of the project
     */
    type?: string;
    /**
     * The original release date of the project (DateTime ISO8601)
     */
    originalReleaseDate?: string;
    /**
     * The record label of the project
     */
    recordLabel?: string;
    /**
     * The publisher of the project
     */
    publisher?: string;
    /**
     * The UPC of the project
     */
    upc?: string;
    [k: string]: unknown;
  };
  /**
   * The artwork of the track
   */
  artwork?: {
    /**
     * The uri of the artwork (ipfs://<CID>)
     */
    uri: string;
    /**
     * The mime type of the artwork
     */
    mimeType: string;
    /**
     * The NFT of the artwork (caip19)
     */
    nft?: string;
    [k: string]: unknown;
  };
  /**
   * The visualizer of the track
   */
  visualizer?: {
    /**
     * The uri of the visualizer (ipfs://<CID>)
     */
    uri: string;
    /**
     * The mime type of the visualizer
     */
    mimeType: string;
    /**
     * The NFT of the visualizer (caip19)
     */
    nft?: string;
    [k: string]: unknown;
  };
  /**
   * The genre of the track
   */
  genre?: string;
  /**
   * The tags of the track
   */
  tags?: string[];
  /**
   * The lyrics of the track
   */
  lyrics?: {
    /**
     * The text of the lyrics
     */
    text: string;
    /**
     * The NFT of the lyrics (caip19)
     */
    nft?: string;
    [k: string]: unknown;
  };
  /**
   * The BPM of the track
   */
  bpm?: number;
  /**
   * The key of the track
   */
  key?: string;
  /**
   * The license of the track
   */
  license: string;
  /**
   * The ISRC of the track
   */
  isrc?: string;
  /**
   * The location where the track was created
   */
  locationCreated?: string;
  /**
   * The original release date of the track (DateTime ISO8601)
   */
  originalReleaseDate?: string;
  /**
   * The record label of the track
   */
  recordLabel?: string;
  /**
   * The publisher of the track
   */
  publisher?: string;
  /**
   * The credits of the track
   */
  credits?: {
    /**
     * The name of the credit
     */
    name: string;
    /**
     * The type of the collaborator
     */
    collaboratorType?: string;
    [k: string]: unknown;
  }[];
  /**
   * The lossless audio URI of the track
   */
  losslessAudio: string;
  /**
   * The image URI of the track
   */
  image: string;
  /**
   * The name of the track (<artist> - <title>)
   */
  name: string;
  /**
   * The external url of the track
   */
  external_url: string;
  /**
   * The animation url of the track
   */
  animation_url: string;
  /**
   * OpenSea NFT Metadata standard attribute tags
   */
  attributes?: {
    /**
     * The artist of the track
     */
    artist: string;
    /**
     * The project of the track
     */
    project?: string;
    /**
     * The BPM of the track
     */
    bpm?: number;
    /**
     * The key of the track
     */
    key?: string;
    /**
     * The genre of the track
     */
    genre?: string;
    /**
     * The record label of the track
     */
    recordLabel?: string;
    /**
     * The license of the track
     */
    license?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
